# crpd_article_dict.py
# Converted from CRPD_DictCode.Rmd (GitHub version by Theodore Ochieng)
# Expanded and refined for the CRPD Dashboard — generic single-word terms
# replaced with more specific multi-word phrases; thin articles augmented.

ARTICLE_PRESETS = {
    "Article 1 — Purpose": [
        "promote respect",
        "physical impairment",
        "mental impairment",
        "sensory impairment",
        "attitudinal barrier",
        "environmental barrier",
        "full participation",
        "persons with disabilities",
        "long-term impairment",
    ],
    "Article 2 — Definitions": [
        "reasonable accommodation",
        "undue burden",
        "assistive technology",
        "plain language",
        "augmentative communication",
        "tactile",
        "communication format",
        "distinction exclusion restriction",
        "nullify or impair",
        "non-spoken language",
        "multimedia",
    ],
    "Article 3 — General Principles": [
        "inherent dignity",
        "individual autonomy",
        "non-discrimination",
        "full inclusion",
        "respect for difference",
        "equal opportunity",
        "accessibility principle",
        "human diversity",
        "gender equality",
    ],
    "Article 4 — General Obligations": [
        "legislative measures",
        "administrative measures",
        "abolish discriminatory practices",
        "universal design",
        "research and development",
        "progressive realization",
        "training of professionals",
        "adopt all appropriate measures",
        "consult with persons with disabilities",
    ],
    "Article 5 — Equality and Non-Discrimination": [
        "equal protection",
        "equal benefit",
        "promote equality",
        "de facto equality",
        "denial of reasonable accommodation",
        "discrimination on the basis of disability",
        "multiple and intersecting discrimination",
    ],
    "Article 6 — Women with Disabilities": [
        "women with disabilities",
        "girls with disabilities",
        "multiple discrimination",
        "gender-based discrimination",
        "intersectional discrimination",
        "empowerment of women",
        "gender equality disability",
        "sexual and reproductive rights",
    ],
    "Article 7 — Children with Disabilities": [
        "children with disabilities",
        "best interests of the child",
        "child rights disability",
        "views of the child",
        "early intervention",
        "child protection disability",
        "maturity of the child",
        "due weight opinions child",
    ],
    "Article 8 — Awareness-raising": [
        "raise awareness",
        "combat stereotypes",
        "promote awareness",
        "public awareness disability",
        "positive perception",
        "awareness-raising campaign",
        "media portrayal disability",
        "challenge misconceptions",
    ],
    "Article 9 — Accessibility": [
        "physical accessibility",
        "built environment",
        "information accessibility",
        "communication accessibility",
        "universal access",
        "accessible buildings",
        "accessible transport",
        "accessible information technology",
        "minimum accessibility standards",
        "assistive technology access",
        "access audit",
    ],
    "Article 10 — Right to Life": [
        "right to life",
        "equal basis life",
        "inherent right to life",
        "deprivation of life",
        "survival and development",
        "life-sustaining treatment",
        "threat to life disability",
    ],
    "Article 11 — Situations of Risk and Humanitarian Emergencies": [
        "disaster risk reduction",
        "humanitarian crisis",
        "armed conflict",
        "emergency situation disability",
        "disaster response",
        "refugee with disability",
        "natural disaster",
        "climate emergency",
        "inclusive humanitarian",
    ],
    "Article 12 — Equal Recognition Before the Law": [
        "legal capacity",
        "substitute decision-making",
        "supported decision-making",
        "guardianship",
        "wardship",
        "mental capacity",
        "personhood",
        "equal recognition before the law",
        "abuse prevention legal",
        "impartial authority",
    ],
    "Article 13 — Access to Justice": [
        "access to justice",
        "procedural accommodation",
        "age appropriate accommodation",
        "legal proceeding",
        "administration of justice",
        "police disability",
        "prison disability",
        "fair trial",
        "legal aid",
        "court accessibility",
        "lawyer disability",
        "witness disability",
    ],
    "Article 14 — Liberty and Security of Person": [
        "deprivation of liberty",
        "mental health detention",
        "involuntary hospitalization",
        "unlawful detention",
        "security of person",
        "liberty on equal basis",
        "disability-based detention",
        "compulsory treatment",
    ],
    "Article 15 — Freedom from Torture": [
        "torture disability",
        "inhuman treatment",
        "degrading treatment",
        "cruel punishment",
        "medical experimentation",
        "non-consensual treatment",
        "forced treatment disability",
        "freedom from torture",
    ],
    "Article 16 — Freedom from Exploitation, Violence and Abuse": [
        "exploitation disability",
        "violence against persons with disabilities",
        "gender-based violence disability",
        "caregiver abuse",
        "protection services disability",
        "psychological recovery",
        "institutional abuse",
        "trafficking disability",
        "sexual abuse disability",
    ],
    "Article 17 — Integrity of the Person": [
        "bodily integrity",
        "physical integrity disability",
        "forced sterilization",
        "involuntary surgery",
        "non-consensual medical intervention",
        "forced medication",
        "personal integrity disability",
        "reproductive autonomy",
    ],
    "Article 18 — Liberty of Movement and Nationality": [
        "freedom of movement disability",
        "right to nationality",
        "statelessness disability",
        "birth registration",
        "travel document disability",
        "immigration disability",
        "border crossing disability",
        "right to leave country",
    ],
    "Article 19 — Independent Living": [
        "independent living",
        "community living",
        "deinstitutionalization",
        "personal assistance",
        "community support services",
        "right to live independently",
        "choice of residence",
        "supported living",
        "isolation institution",
    ],
    "Article 20 — Personal Mobility": [
        "personal mobility",
        "mobility aids",
        "wheelchair",
        "prosthetics disability",
        "orientation and mobility",
        "affordable mobility devices",
        "mobility training",
        "assistive devices mobility",
    ],
    "Article 21 — Freedom of Expression and Access to Information": [
        "freedom of expression disability",
        "access to information disability",
        "sign language",
        "braille",
        "augmentative and alternative communication",
        "accessible media",
        "accessible internet",
        "easy read format",
        "accessible communication formats",
    ],
    "Article 22 — Privacy": [
        "privacy disability",
        "personal data protection",
        "medical records confidentiality",
        "unlawful interference privacy",
        "correspondence privacy",
        "right to privacy disability",
        "surveillance disability",
        "data privacy persons with disabilities",
    ],
    "Article 23 — Home and Family": [
        "marriage disability",
        "family life disability",
        "reproductive rights disability",
        "parental rights disability",
        "child custody disability",
        "child rearing disability",
        "family planning disability",
        "separation of children",
    ],
    "Article 24 — Education": [
        "inclusive education",
        "special education",
        "reasonable accommodation education",
        "sign language instruction",
        "accessible curriculum",
        "teacher training disability",
        "lifelong learning disability",
        "free primary education",
        "tertiary education disability",
        "individualized support education",
    ],
    "Article 25 — Health": [
        "healthcare disability",
        "reproductive health disability",
        "mental health services",
        "health insurance disability",
        "free informed consent health",
        "primary health care disability",
        "affordable health services",
        "sexual health disability",
        "health professional training disability",
    ],
    "Article 26 — Habilitation and Rehabilitation": [
        "habilitation",
        "rehabilitation disability",
        "community-based rehabilitation",
        "physical therapy disability",
        "occupational therapy",
        "peer support disability",
        "early childhood intervention",
        "assistive device rehabilitation",
        "vocational rehabilitation",
    ],
    "Article 27 — Work and Employment": [
        "employment disability",
        "workplace accommodation",
        "open labour market",
        "sheltered workshop",
        "equal remuneration disability",
        "vocational training disability",
        "self-employment disability",
        "labour rights disability",
        "career advancement disability",
    ],
    "Article 28 — Standard of Living": [
        "adequate standard of living",
        "social protection disability",
        "poverty reduction disability",
        "social security disability",
        "disability benefit",
        "housing disability",
        "food security disability",
        "financial assistance disability",
    ],
    "Article 29 — Political and Public Life": [
        "right to vote disability",
        "electoral process disability",
        "political participation disability",
        "run for election disability",
        "secret ballot accessibility",
        "civil society disability",
        "public affairs disability",
        "civic participation",
    ],
    "Article 30 — Cultural Life and Recreation": [
        "cultural participation disability",
        "accessible cultural events",
        "intellectual property disability",
        "sporting activities disability",
        "leisure disability",
        "recreation disability",
        "accessible tourism",
        "sport for persons with disabilities",
    ],
    "Article 31 — Statistics and Data Collection": [
        "disability data",
        "disaggregated data disability",
        "disability statistics",
        "census disability",
        "data collection disability",
        "disability research data",
        "data protection disability",
        "statistical information disability",
    ],
    "Article 32 — International Cooperation": [
        "international development disability",
        "development cooperation disability",
        "overseas development disability",
        "bilateral assistance disability",
        "sustainable development goals disability",
        "technical assistance disability",
        "capacity building disability",
    ],
    "Article 33 — Implementation and Monitoring": [
        "focal point disability",
        "national monitoring mechanism",
        "independent monitoring disability",
        "national human rights institution",
        "disabled persons organizations",
        "civil society monitoring",
        "Paris Principles",
        "coordination mechanism disability",
        "CRPD implementation",
    ],
    "Article 34 — Committee on the Rights of Persons with Disabilities": [
        "committee membership",
        "committee election",
        "committee on the rights of persons with disabilities",
        "expert committee CRPD",
        "CRPD committee composition",
    ],
    "Article 35 — Reports by States Parties": [
        "state party report",
        "initial report CRPD",
        "periodic report disability",
        "submission to committee",
        "reporting obligation CRPD",
        "progress report CRPD",
    ],
    "Article 36 — Consideration of Reports": [
        "consideration of reports",
        "report review committee",
        "committee review CRPD",
        "list of issues",
        "concluding observations",
        "reporting cycle",
    ],
    "Article 37 — Cooperation between States Parties": [
        "inter-state cooperation disability",
        "cooperation between states parties",
        "mutual assistance CRPD",
    ],
    "Article 38 — Relationship with Other Bodies": [
        "relationship with UN bodies",
        "expert advice disability",
        "specialized agencies disability",
        "OHCHR CRPD",
        "UN system disability",
    ],
    "Article 39 — Report of the Committee": [
        "report of the committee",
        "general assembly CRPD",
        "committee annual report",
        "committee examination report",
    ],
    "Article 40 — Conference of States Parties": [
        "conference of states parties",
        "states parties meeting",
        "CRPD conference",
        "implementation conference",
    ],
    "Article 41 — Depositary": [
        "depositary",
        "UN Secretary-General depositary",
        "UN headquarters CRPD",
    ],
    "Article 42 — Signature": [
        "open for signature",
        "signature CRPD convention",
        "headquarters signing",
    ],
    "Article 43 — Consent to be Bound": [
        "ratification CRPD",
        "accession CRPD",
        "formal confirmation",
        "consent to be bound",
    ],
    "Article 44 — Regional Integration Organizations": [
        "regional integration organization",
        "regional competence disability",
        "regional organization CRPD",
    ],
    "Article 45 — Entry into Force": [
        "entry into force CRPD",
        "twentieth ratification",
        "convention enters into force",
    ],
    "Article 46 — Reservations": [
        "reservation CRPD",
        "reservation withdrawn",
        "incompatible reservation",
        "object and purpose CRPD",
    ],
    "Article 47 — Amendments": [
        "amendment CRPD",
        "amendment adoption",
        "amendment consensus",
        "proposed amendment convention",
    ],
    "Article 48 — Denunciation": [
        "denounce convention",
        "denunciation CRPD",
        "withdrawal notification",
        "denounce treaty",
    ],
    "Article 49 — Accessible Format": [
        "accessible format convention",
        "accessible text CRPD",
        "convention in accessible format",
    ],
    "Article 50 — Authentic Texts": [
        "authentic text convention",
        "authentic languages CRPD",
        "equally authentic",
    ],
}
