"""PDF and DOCX export for CRPD research briefings."""

from __future__ import annotations

from datetime import UTC, datetime
import io
import re

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor
from fpdf import FPDF


# ── Helpers ───────────────────────────────────────────────────────────────────

_FOOTER_TEXT = (
    "AI-generated analysis. Not a legal assessment. Verify against original UN documents."
)

_DISCLAIMER = (
    "This is not a United Nations document. Generated by AI-powered research "
    "assistant using keyword-based text analysis of official UN treaty body "
    "documents. This does not constitute a legal assessment."
)


def _unique_sources(result: dict) -> list[str]:
    """Extract unique source lines from all_chunks."""
    all_chunks = result.get("all_chunks", [])
    seen: set[str] = set()
    sources: list[str] = []
    for c in all_chunks:
        country = c.get("country", "Unknown")
        doc_type = c.get("doc_type", "Unknown")
        year = c.get("year", "Unknown")
        symbol = c.get("un_symbol", "")
        key = f"{country}|{doc_type}|{year}"
        if key not in seen:
            seen.add(key)
            line = f"{country}, {doc_type}, {year}"
            if symbol:
                line += f" ({symbol})"
            sources.append(line)
    return sources


def _split_briefing(briefing: str) -> tuple[str, str]:
    """Split briefing into executive summary (first paragraph) and findings."""
    paragraphs = [p.strip() for p in briefing.split("\n\n") if p.strip()]
    if len(paragraphs) <= 1:
        return briefing.strip(), ""
    return paragraphs[0], "\n\n".join(paragraphs[1:])


def _clean_markdown(text: str) -> str:
    """Strip markdown formatting for plain-text rendering in PDF."""
    # Remove bold/italic markers
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    # Remove heading markers
    text = re.sub(r"^#{1,4}\s*", "", text, flags=re.MULTILINE)
    # Remove bullet markers (replace with dash)
    text = re.sub(r"^\s*[-*]\s+", "- ", text, flags=re.MULTILINE)
    return text.strip()


# ── PDF Export ────────────────────────────────────────────────────────────────


class _BriefingPDF(FPDF):
    """Custom FPDF subclass with running footer."""

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, _FOOTER_TEXT, align="C")


def export_briefing_pdf(result: dict, methodology: str, stats: dict) -> bytes:
    """Generate a formatted PDF briefing and return as bytes.

    Parameters
    ----------
    result : dict
        Pipeline result dict from ``run_research_pipeline``.
    methodology : str
        Markdown methodology appendix text.
    stats : dict
        Dataset statistics from ``get_dataset_stats()``.

    Returns
    -------
    bytes
        PDF file content.
    """
    pdf = _BriefingPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    # -- Cover page --
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 24)
    pdf.ln(40)
    pdf.cell(0, 14, "CRPD Research Briefing", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(120, 0, 0)
    pdf.multi_cell(0, 5, _DISCLAIMER, align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)

    pdf.set_font("Helvetica", "B", 12)
    pdf.multi_cell(0, 7, f"Query: {result.get('query', '')}", align="C")
    pdf.ln(6)

    _date_str = datetime.now(tz=UTC).strftime("%Y-%m-%d")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Date: {_date_str}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    n_chunks = len(result.get("all_chunks", []))
    n_countries = len(set(c.get("country", "") for c in result.get("all_chunks", [])))
    pdf.multi_cell(
        0,
        5,
        (
            f"Corpus: {stats.get('n_docs', 0)} documents across "
            f"{stats.get('n_countries', 0)} States Parties "
            f"({stats.get('year_min', 0)}-{stats.get('year_max', 0)}). "
            f"This briefing drew on {n_chunks} excerpts from "
            f"{n_countries} States Parties."
        ),
        align="C",
    )

    # -- Executive Summary --
    briefing = result.get("briefing", "")
    exec_summary, findings = _split_briefing(briefing)

    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Executive Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 5, _clean_markdown(exec_summary))
    pdf.ln(6)

    # -- Findings --
    if findings:
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, "Findings", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 10)
        # Process findings paragraph by paragraph
        for para in findings.split("\n\n"):
            clean = _clean_markdown(para.strip())
            if not clean:
                continue
            # Check if it looks like a heading (short, no period at end)
            if len(clean) < 80 and not clean.endswith(".") and not clean.startswith("-"):
                pdf.set_font("Helvetica", "B", 11)
                pdf.ln(4)
                pdf.cell(0, 6, clean, new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "", 10)
            else:
                pdf.multi_cell(0, 5, clean)
            pdf.ln(3)

    # -- Methodology Appendix --
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Methodology Appendix", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 9)
    for para in _clean_markdown(methodology).split("\n\n"):
        clean = para.strip()
        if not clean:
            continue
        # Section headings (lines starting with a number and period)
        if re.match(r"^\d+\.", clean) and len(clean) < 60:
            pdf.set_font("Helvetica", "B", 10)
            pdf.ln(4)
            pdf.cell(0, 6, clean, new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
        else:
            pdf.multi_cell(0, 4.5, clean)
        pdf.ln(2)

    # -- Sources --
    sources = _unique_sources(result)
    if sources:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, "Sources", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 9)
        for src in sources:
            pdf.multi_cell(0, 4.5, f"- {src}")
            pdf.ln(1)

    # Output
    buf = io.BytesIO()
    buf.write(pdf.output())
    return buf.getvalue()


# ── DOCX Export ───────────────────────────────────────────────────────────────


def export_briefing_docx(result: dict, methodology: str, stats: dict) -> bytes:
    """Generate a formatted DOCX briefing and return as bytes.

    Parameters
    ----------
    result : dict
        Pipeline result dict from ``run_research_pipeline``.
    methodology : str
        Markdown methodology appendix text.
    stats : dict
        Dataset statistics from ``get_dataset_stats()``.

    Returns
    -------
    bytes
        DOCX file content.
    """
    doc = Document()

    # -- Styles --
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)

    # -- Cover page --
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title_para.add_run("CRPD Research Briefing")
    title_run.bold = True
    title_run.font.size = Pt(24)
    title_run.font.color.rgb = RGBColor(0, 63, 135)

    disclaimer_para = doc.add_paragraph()
    disclaimer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    disc_run = disclaimer_para.add_run(_DISCLAIMER)
    disc_run.font.size = Pt(9)
    disc_run.font.color.rgb = RGBColor(150, 0, 0)

    query_para = doc.add_paragraph()
    query_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    q_run = query_para.add_run(f"Query: {result.get('query', '')}")
    q_run.bold = True
    q_run.font.size = Pt(12)

    _date_str = datetime.now(tz=UTC).strftime("%Y-%m-%d")
    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_para.add_run(f"Date: {_date_str}")

    n_chunks = len(result.get("all_chunks", []))
    n_countries = len(set(c.get("country", "") for c in result.get("all_chunks", [])))
    corpus_para = doc.add_paragraph()
    corpus_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    corpus_para.add_run(
        f"Corpus: {stats.get('n_docs', 0)} documents across "
        f"{stats.get('n_countries', 0)} States Parties "
        f"({stats.get('year_min', 0)}-{stats.get('year_max', 0)}). "
        f"This briefing drew on {n_chunks} excerpts from "
        f"{n_countries} States Parties."
    )

    doc.add_page_break()

    # -- Executive Summary --
    briefing = result.get("briefing", "")
    exec_summary, findings = _split_briefing(briefing)

    doc.add_heading("Executive Summary", level=1)
    doc.add_paragraph(_clean_markdown(exec_summary))

    # -- Findings --
    if findings:
        doc.add_heading("Findings", level=1)
        for para in findings.split("\n\n"):
            clean = _clean_markdown(para.strip())
            if not clean:
                continue
            if len(clean) < 80 and not clean.endswith(".") and not clean.startswith("-"):
                doc.add_heading(clean, level=2)
            else:
                doc.add_paragraph(clean)

    # -- Methodology Appendix --
    doc.add_page_break()
    doc.add_heading("Methodology Appendix", level=1)
    for para in methodology.split("\n"):
        line = para.strip()
        if not line:
            continue
        # Section headings
        if line.startswith("### "):
            doc.add_heading(line.replace("### ", ""), level=2)
        else:
            p = doc.add_paragraph(_clean_markdown(line))
            p.paragraph_format.space_after = Pt(4)

    # -- Sources --
    sources = _unique_sources(result)
    if sources:
        doc.add_page_break()
        doc.add_heading("Sources", level=1)
        for src in sources:
            doc.add_paragraph(src, style="List Bullet")

    # -- Footer note --
    doc.add_paragraph()
    footer_para = doc.add_paragraph()
    footer_run = footer_para.add_run(_FOOTER_TEXT)
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(100, 100, 100)
    footer_run.italic = True

    # Output
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
